url: http://kirbyt.github.io/timeline-jekyll-theme
baseurl: 

# Site Settings
title: Timeline
description: "Timeline is multipurpose, single page Jekyll theme that includes a timeline section."
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
